Main has new option for printing the whole image instead of the small outputs. By changing whole_image_output = True/False Bug with saving the image in the 50th epoch 😰
MemoryError: Unable to allocate 312. KiB for an array with shape (100, 100, 4) and data type float64